### ISSUE TITLE
Improve Locale Interceptor OR permanently add lang= param to url

### ISSUE THREAD

**Issue by jhaydtw** [wet-boew/spring-boot-thymeleaf#42]
When accessing our web pages at the base url, there is no lang= parameter in the url.  Therefore the language interceptor fails the "if (locale != null) " check on line 27 and falls through without doing anything.  The issue with this is that there are two use cases where this fails to set the language correctly, and the language defaults to english.  The use cases are "Accessing the base url from a French OS/browser" and "Using the timeout dialogue button to start a new session in a French session."

These can be accommodated in two ways:
Always attach the lang= parameter to the url.  Not sure how feasible this is.
Update the interceptor to handle the locale=null case.  It can use Locale resolveLocale(HttpServletRequest request) from org.springframework.web.servlet.LocaleResolver to get the language from the request.

We will try to work around these two issues by implementing a filter that adds the lang= parameter to the url - a bit of a hack.

**Comment by sellersj** [comment]
I don't have the code in front of me right now, so this is going from memory:

We used a custom locale resolver that would force Canadian English or Canadian French (otherwise you could get GB locales which can display pounds for currency). It either extended the session resolver or did the same behavior.

For logout or session expiry widget I believe it explicitly added the lang parm.

I hope this helps.

**Comment by jhaydtw** [comment]
@sellersj - session expiry is not adding lang to the url, which is the root of the problem.  Is the logout destination configurable using cdn-override.properties?

**Comment by jhaydtw** [comment]
Turns out that we had a misconfiguration in our code.  We had invoked the timeout using a spring property for the arguments, but did not have the property configured.  Initializing the sessto tag without parameters causes the behaviour described.  Once the parameter was defined with valid arguments the issue goes away.  Not sure what the difference is, but not your fault, so will close the ticket.

**Comment by sellersj** [comment]
Glad you were able to solve it!
