### ISSUE TITLE
Minor error in instructions on Building wet-cdts-spring-boot-thymeleaf-starter

### ISSUE THREAD

**Issue by pardxa** [wet-boew/spring-boot-thymeleaf#43]
In Readme, Building wet-cdts-spring-boot-thymeleaf-starter
After the clone step, the maven command should be ` mvn install -Dmaven.test.skip=true`
Otherwise, the errors in the testing process will stop the installing session.

**Comment by sellersj** [comment]
@pardxa  What tests are failing for you? All pass for me on multiple computers.

One thing is the current version requires you use java 7 to build it, otherwise it might default to a different version. Java 8 works for master as well.

**Comment by sellersj** [comment]
Actually, I think that I've reproduced it now. Let me look into it.

**Comment by sellersj** [comment]
@pardxa please let me know if you are still having issues. For master that uses spring boot 1.3, you must use java 7 or 8. There was other branches that were not released for spring boot 2 and 3 that would run with java 11 or 17.
